### ISSUE TITLE
tracking down the problem behind a "No new payments found" message

### ISSUE THREAD

**Issue by freggala** [jHetzer/erpnextfints#11]
I eventually managed to set up ERPNextFinTS and configure a couple of bank accounts (Volksbank, Sparkasse). When trying to carry out a FinTS Import everything seems to work well, except it never seems to retrieve any actual payments and finishes with the message "No new payments found" (however there are/were (new) payments in the interval specified by "From Date" and "To Date").

What could be going wrong here?
How can I narrow down the issue?
Is it possible to retrieve payments from a bank that have been checked out previously using another Online-Banking software (also via HBCI/FinTS)?
(It seems these payments get flagged as 'read' as soon as they've been successfully delivered to a client.)

@jHetzer: Is there a way to contact you in person?

Thank you very much in advance!

**Comment by jHetzer** [comment]
As far as I know FinTS does not mark any transaction as "read"/"retrieved". Could you please share an anonymized print screen of your "FinTS Login" config. Especially the default customer and default supplier settings.
Regarding some basic "tracking down" of imports I hope I can realize the import history as soon as possible.

**Comment by jHetzer** [comment]
For some manual checks you could try following:
switch to your bench installation folder (/home/frappe/frappe-bench)
```
bench console

from erpnextfints.utils.fints_controller import FinTSController
from dateutil.relativedelta import relativedelta
from frappe.utils import now_datetime

frappe.get_all("FinTS Login")

fintscon = FinTSController('Some FinTS Login Name')
fintscon.get_fints_accounts()
start_date = now_datetime().date() - relativedelta(days=30)
end_date = now_datetime().date() - relativedelta(days=1)

fintscon.get_fints_transactions(start_date, end_date)
```

and check or provide the anonymized output.

**Comment by freggala** [comment]
Ok, thank you very much for the detailed instructions. I tried it out and it worked like a charm. I'm receiving transactions from my bank, so the problem must be located somewhere in the successive processing of that data.
In  ERPNext I tried to view the "Payment Entry" list/report and I always get that "re.error: bad escape \d at position 1054 (line 20, column 35)" server error (like with everything else that is somehow related to Payment Entries).

It looks like that is an ERPNext problem rather than one of the FinTS plugin and I'll try to further investigate that.

**Comment by jHetzer** [comment]
Which branch(s) are currently you using (frappe/erpnext/erpnextfints/custom apps)?
Are you working in frappe production or developer mode?
Did the browser console log any errors?

ERPNextFinTS is customizing the "Payment Entry" doctype, there might be an issue there.

**Comment by freggala** [comment]
Regarding the versions used, this is what "bench version" reports:
```
erpnext 12.x.x-develop
erpnextfints 0.2.0
frappe 12.x.x-develop
```
So yes, it's in developer mode.
To make the "Report" button work, I had to fix a couple of other problems, but now I get some more promising information:





```
Route
List/Payment Entry
Error Report
Traceback (most recent call last):
  File "/opt/erpnext/env/lib/python3.7/sre_parse.py", line 1021, in parse_template
    this = chr(ESCAPES[this][1])
KeyError: '\\d'
```
and:
```
Traceback (most recent call last):
  File "/opt/erpnext/apps/frappe/frappe/app.py", line 60, in application
    response = frappe.api.handle()
  File "/opt/erpnext/apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "/opt/erpnext/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/opt/erpnext/apps/frappe/frappe/handler.py", line 61, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/opt/erpnext/apps/frappe/frappe/__init__.py", line 1053, in call
    return fn(*args, **newargs)
  File "/opt/erpnext/apps/frappe/frappe/desk/form/load.py", line 69, in getdoctype
    docs = get_meta_bundle(doctype)
  File "/opt/erpnext/apps/frappe/frappe/desk/form/load.py", line 79, in get_meta_bundle
    bundle = [frappe.desk.form.meta.get_meta(doctype)]
  File "/opt/erpnext/apps/frappe/frappe/desk/form/meta.py", line 26, in get_meta
    meta = FormMeta(doctype)
  File "/opt/erpnext/apps/frappe/frappe/desk/form/meta.py", line 39, in __init__
    self.load_assets()
  File "/opt/erpnext/apps/frappe/frappe/desk/form/meta.py", line 49, in load_assets
    self.add_code()
  File "/opt/erpnext/apps/frappe/frappe/desk/form/meta.py", line 103, in add_code
    self.add_code_via_hook("doctype_js", "__js")
  File "/opt/erpnext/apps/frappe/frappe/desk/form/meta.py", line 128, in add_code_via_hook
    self._add_code(path, fieldname)
  File "/opt/erpnext/apps/frappe/frappe/desk/form/meta.py", line 110, in _add_code
    js = get_js(path)
  File "/opt/erpnext/apps/frappe/frappe/desk/form/meta.py", line 235, in get_js
    return render_include(js)
  File "/opt/erpnext/apps/frappe/frappe/model/utils/__init__.py", line 75, in render_include
    content = re.sub(r'''{{% include\s['"]{0}['"]\s%}}'''.format(path), include, content)
  File "/opt/erpnext/env/lib/python3.7/re.py", line 192, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/opt/erpnext/env/lib/python3.7/re.py", line 309, in _subx
    template = _compile_repl(template, pattern)
  File "/opt/erpnext/env/lib/python3.7/re.py", line 300, in _compile_repl
    return sre_parse.parse_template(repl, pattern)
  File "/opt/erpnext/env/lib/python3.7/sre_parse.py", line 1024, in parse_template
    raise s.error('bad escape %s' % this, len(this))
re.error: bad escape \d at position 1054 (line 20, column 35)
Request Data
{
	"type": "GET",
	"args": {
		"doctype": "Payment Entry",
		"with_parent": 1,
		"cached_timestamp": null
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.load.getdoctype"
}
```
This matches the message in the browser console.

**Comment by freggala** [comment]
Is the master branch of ERPNextFinTS compatible with the development branch of ERPNext?

**Comment by jHetzer** [comment]
ERPNextFinTS is only tested against the production branches (version-11 / version-12) and I would recommend to use them. It's likely that develop branches have some issues.
