### ISSUE TITLE
frappe check_for_update creates daily errors

### ISSUE THREAD

**Issue by jHetzer** [jHetzer/erpnextfints#37]
`frappe.utils.change_log.check_for_update`

```python
{'method_name': 'frappe.utils.change_log.check_for_update', 'log': <function log at 0x7f39e14240d0>, 'retry': 0, 'is_async': True, 'user': 'Administrator', 'kwargs': {}, 'job_name': 'frappe.utils.change_log.check_for_update', 'event': 'daily_long', 'method': <function check_for_update at 0x7f39e18d56a8>, 'site': 'erpnext.butzenhof.de'}
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 102, in execute_job
    method(**kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/change_log.py", line 144, in check_for_update
    app_details = check_release_on_github(app)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/change_log.py", line 207, in check_release_on_github
    return Version(lastest_non_beta_release), org_name
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/semantic_version/base.py", line 102, in __init__
    raise ValueError("Call either Version('1.2.3') or Version(major=1, ...).")
ValueError: Call either Version('1.2.3') or Version(major=1, ...).
```

**Comment by jHetzer** [comment]
ERPNextFinTS had no releases. (0.3.4 published as release now)
frappe code for reference:
```python
	org_name = remote_url.split('/')[3]
	r = requests.get('https://api.github.com/repos/{}/{}/releases'.format(org_name, app))
	if r.ok:
		lastest_non_beta_release = parse_latest_non_beta_release(r.json())
		return Version(lastest_non_beta_release), org_name
	# In case of an improper response or if there are no releases
	return None
```

https://github.com/frappe/frappe/blob/fd1453860c1b9ae6583e92fcbf67a0f9d2e80f3a/frappe/utils/change_log.py#L204
